mod app;
mod value_objects;
pub use app::KanjiTreeApp;
mod kigou_source; 
mod kigou_parser; 
mod message;
mod kigou_button;
mod kigou_panel;
mod kigou_display_active;
mod kigou_display_buttons;
mod reload_button;
mod search_panel;
mod fonts;
mod validation_error;
